// ============================================================
// Major North American cities for the city autocomplete.
// Each entry has a city name and state/province abbreviation
// so selecting a city can auto-fill the State field too.
//
// To add more cities: append to the list below.
// The combobox filters by label + sublabel so typing either
// the city name or state code will surface results.
// ============================================================

export interface CityEntry {
  city:    string
  state:   string   // state / province abbreviation
  country: 'US' | 'CA' | 'MX'
}

export const MAJOR_CITIES: CityEntry[] = [

  // ── United States — Top 100 metros ────────────────────────────────────────

  { city: 'New York',           state: 'NY', country: 'US' },
  { city: 'Los Angeles',        state: 'CA', country: 'US' },
  { city: 'Chicago',            state: 'IL', country: 'US' },
  { city: 'Houston',            state: 'TX', country: 'US' },
  { city: 'Phoenix',            state: 'AZ', country: 'US' },
  { city: 'Philadelphia',       state: 'PA', country: 'US' },
  { city: 'San Antonio',        state: 'TX', country: 'US' },
  { city: 'San Diego',          state: 'CA', country: 'US' },
  { city: 'Dallas',             state: 'TX', country: 'US' },
  { city: 'San Jose',           state: 'CA', country: 'US' },
  { city: 'Austin',             state: 'TX', country: 'US' },
  { city: 'Jacksonville',       state: 'FL', country: 'US' },
  { city: 'Fort Worth',         state: 'TX', country: 'US' },
  { city: 'Columbus',           state: 'OH', country: 'US' },
  { city: 'Charlotte',          state: 'NC', country: 'US' },
  { city: 'Indianapolis',       state: 'IN', country: 'US' },
  { city: 'San Francisco',      state: 'CA', country: 'US' },
  { city: 'Seattle',            state: 'WA', country: 'US' },
  { city: 'Denver',             state: 'CO', country: 'US' },
  { city: 'Nashville',          state: 'TN', country: 'US' },
  { city: 'Oklahoma City',      state: 'OK', country: 'US' },
  { city: 'El Paso',            state: 'TX', country: 'US' },
  { city: 'Washington',         state: 'DC', country: 'US' },
  { city: 'Las Vegas',          state: 'NV', country: 'US' },
  { city: 'Louisville',         state: 'KY', country: 'US' },
  { city: 'Memphis',            state: 'TN', country: 'US' },
  { city: 'Portland',           state: 'OR', country: 'US' },
  { city: 'Baltimore',          state: 'MD', country: 'US' },
  { city: 'Milwaukee',          state: 'WI', country: 'US' },
  { city: 'Albuquerque',        state: 'NM', country: 'US' },
  { city: 'Tucson',             state: 'AZ', country: 'US' },
  { city: 'Fresno',             state: 'CA', country: 'US' },
  { city: 'Sacramento',         state: 'CA', country: 'US' },
  { city: 'Mesa',               state: 'AZ', country: 'US' },
  { city: 'Kansas City',        state: 'MO', country: 'US' },
  { city: 'Atlanta',            state: 'GA', country: 'US' },
  { city: 'Omaha',              state: 'NE', country: 'US' },
  { city: 'Colorado Springs',   state: 'CO', country: 'US' },
  { city: 'Raleigh',            state: 'NC', country: 'US' },
  { city: 'Long Beach',         state: 'CA', country: 'US' },
  { city: 'Virginia Beach',     state: 'VA', country: 'US' },
  { city: 'Minneapolis',        state: 'MN', country: 'US' },
  { city: 'Tampa',              state: 'FL', country: 'US' },
  { city: 'New Orleans',        state: 'LA', country: 'US' },
  { city: 'Arlington',          state: 'TX', country: 'US' },
  { city: 'Bakersfield',        state: 'CA', country: 'US' },
  { city: 'Honolulu',           state: 'HI', country: 'US' },
  { city: 'Anaheim',            state: 'CA', country: 'US' },
  { city: 'Aurora',             state: 'CO', country: 'US' },
  { city: 'Santa Ana',          state: 'CA', country: 'US' },
  { city: 'Corpus Christi',     state: 'TX', country: 'US' },
  { city: 'Riverside',          state: 'CA', country: 'US' },
  { city: 'Lexington',          state: 'KY', country: 'US' },
  { city: 'St. Louis',          state: 'MO', country: 'US' },
  { city: 'Pittsburgh',         state: 'PA', country: 'US' },
  { city: 'Anchorage',          state: 'AK', country: 'US' },
  { city: 'Stockton',           state: 'CA', country: 'US' },
  { city: 'Cincinnati',         state: 'OH', country: 'US' },
  { city: 'St. Paul',           state: 'MN', country: 'US' },
  { city: 'Greensboro',         state: 'NC', country: 'US' },
  { city: 'Toledo',             state: 'OH', country: 'US' },
  { city: 'Newark',             state: 'NJ', country: 'US' },
  { city: 'Plano',              state: 'TX', country: 'US' },
  { city: 'Henderson',          state: 'NV', country: 'US' },
  { city: 'Orlando',            state: 'FL', country: 'US' },
  { city: 'Chandler',           state: 'AZ', country: 'US' },
  { city: 'Laredo',             state: 'TX', country: 'US' },
  { city: 'Norfolk',            state: 'VA', country: 'US' },
  { city: 'Madison',            state: 'WI', country: 'US' },
  { city: 'Durham',             state: 'NC', country: 'US' },
  { city: 'Lubbock',            state: 'TX', country: 'US' },
  { city: 'Winston-Salem',      state: 'NC', country: 'US' },
  { city: 'Garland',            state: 'TX', country: 'US' },
  { city: 'Glendale',           state: 'AZ', country: 'US' },
  { city: 'Hialeah',            state: 'FL', country: 'US' },
  { city: 'Reno',               state: 'NV', country: 'US' },
  { city: 'Baton Rouge',        state: 'LA', country: 'US' },
  { city: 'Irvine',             state: 'CA', country: 'US' },
  { city: 'Chesapeake',         state: 'VA', country: 'US' },
  { city: 'Irving',             state: 'TX', country: 'US' },
  { city: 'Scottsdale',         state: 'AZ', country: 'US' },
  { city: 'North Las Vegas',    state: 'NV', country: 'US' },
  { city: 'Fremont',            state: 'CA', country: 'US' },
  { city: 'Gilbert',            state: 'AZ', country: 'US' },
  { city: 'San Bernardino',     state: 'CA', country: 'US' },
  { city: 'Birmingham',         state: 'AL', country: 'US' },
  { city: 'Rochester',          state: 'NY', country: 'US' },
  { city: 'Richmond',           state: 'VA', country: 'US' },
  { city: 'Spokane',            state: 'WA', country: 'US' },
  { city: 'Des Moines',         state: 'IA', country: 'US' },
  { city: 'Montgomery',         state: 'AL', country: 'US' },
  { city: 'Modesto',            state: 'CA', country: 'US' },
  { city: 'Fayetteville',       state: 'NC', country: 'US' },
  { city: 'Tacoma',             state: 'WA', country: 'US' },
  { city: 'Shreveport',         state: 'LA', country: 'US' },
  { city: 'Fontana',            state: 'CA', country: 'US' },
  { city: 'Moreno Valley',      state: 'CA', country: 'US' },
  { city: 'Glendale',           state: 'CA', country: 'US' },
  { city: 'Akron',              state: 'OH', country: 'US' },
  { city: 'Yonkers',            state: 'NY', country: 'US' },
  { city: 'Huntington Beach',   state: 'CA', country: 'US' },
  { city: 'Little Rock',        state: 'AR', country: 'US' },
  { city: 'Columbus',           state: 'GA', country: 'US' },
  { city: 'Augusta',            state: 'GA', country: 'US' },
  { city: 'Grand Rapids',       state: 'MI', country: 'US' },
  { city: 'Salt Lake City',     state: 'UT', country: 'US' },
  { city: 'Huntsville',         state: 'AL', country: 'US' },
  { city: 'Tallahassee',        state: 'FL', country: 'US' },
  { city: 'Worcester',          state: 'MA', country: 'US' },
  { city: 'Knoxville',          state: 'TN', country: 'US' },
  { city: 'Providence',         state: 'RI', country: 'US' },
  { city: 'Brownsville',        state: 'TX', country: 'US' },
  { city: 'Santa Clarita',      state: 'CA', country: 'US' },
  { city: 'Garden Grove',       state: 'CA', country: 'US' },
  { city: 'Oceanside',          state: 'CA', country: 'US' },
  { city: 'Fort Lauderdale',    state: 'FL', country: 'US' },
  { city: 'Rancho Cucamonga',   state: 'CA', country: 'US' },
  { city: 'Santa Rosa',         state: 'CA', country: 'US' },
  { city: 'Tempe',              state: 'AZ', country: 'US' },
  { city: 'Cape Coral',         state: 'FL', country: 'US' },
  { city: 'Oxnard',             state: 'CA', country: 'US' },
  { city: 'Eugene',             state: 'OR', country: 'US' },
  { city: 'Peoria',             state: 'AZ', country: 'US' },
  { city: 'Salem',              state: 'OR', country: 'US' },
  { city: 'Cary',               state: 'NC', country: 'US' },
  { city: 'Fort Collins',       state: 'CO', country: 'US' },
  { city: 'Jackson',            state: 'MS', country: 'US' },
  { city: 'Alexandria',         state: 'VA', country: 'US' },
  { city: 'Hayward',            state: 'CA', country: 'US' },
  { city: 'Lancaster',          state: 'CA', country: 'US' },
  { city: 'Salinas',            state: 'CA', country: 'US' },
  { city: 'Palmdale',           state: 'CA', country: 'US' },
  { city: 'Sunnyvale',          state: 'CA', country: 'US' },
  { city: 'Pomona',             state: 'CA', country: 'US' },
  { city: 'Escondido',          state: 'CA', country: 'US' },
  { city: 'Kansas City',        state: 'KS', country: 'US' },
  { city: 'Rockford',           state: 'IL', country: 'US' },
  { city: 'Torrance',           state: 'CA', country: 'US' },
  { city: 'Bridgeport',         state: 'CT', country: 'US' },
  { city: 'Syracuse',           state: 'NY', country: 'US' },
  { city: 'Surprise',           state: 'AZ', country: 'US' },
  { city: 'Pasadena',           state: 'CA', country: 'US' },
  { city: 'Savannah',           state: 'GA', country: 'US' },
  { city: 'Hollywood',          state: 'FL', country: 'US' },
  { city: 'Paterson',           state: 'NJ', country: 'US' },
  { city: 'Naperville',         state: 'IL', country: 'US' },
  { city: 'Mesquite',           state: 'TX', country: 'US' },
  { city: 'Clarksville',        state: 'TN', country: 'US' },
  { city: 'Killeen',            state: 'TX', country: 'US' },
  { city: 'Dayton',             state: 'OH', country: 'US' },
  { city: 'Macon',              state: 'GA', country: 'US' },
  { city: 'Waco',               state: 'TX', country: 'US' },
  { city: 'Springfield',        state: 'MO', country: 'US' },
  { city: 'Charleston',         state: 'SC', country: 'US' },
  { city: 'Sioux Falls',        state: 'SD', country: 'US' },
  { city: 'Chattanooga',        state: 'TN', country: 'US' },
  { city: 'Miami',              state: 'FL', country: 'US' },
  { city: 'Boston',             state: 'MA', country: 'US' },
  { city: 'Detroit',            state: 'MI', country: 'US' },
  { city: 'Buffalo',            state: 'NY', country: 'US' },
  { city: 'Tucson',             state: 'AZ', country: 'US' },
  { city: 'Louisville',         state: 'KY', country: 'US' },

  // ── Canada — Major cities ──────────────────────────────────────────────────

  { city: 'Toronto',            state: 'ON', country: 'CA' },
  { city: 'Montreal',           state: 'QC', country: 'CA' },
  { city: 'Vancouver',          state: 'BC', country: 'CA' },
  { city: 'Calgary',            state: 'AB', country: 'CA' },
  { city: 'Edmonton',           state: 'AB', country: 'CA' },
  { city: 'Ottawa',             state: 'ON', country: 'CA' },
  { city: 'Mississauga',        state: 'ON', country: 'CA' },
  { city: 'Winnipeg',           state: 'MB', country: 'CA' },
  { city: 'Quebec City',        state: 'QC', country: 'CA' },
  { city: 'Hamilton',           state: 'ON', country: 'CA' },
  { city: 'Brampton',           state: 'ON', country: 'CA' },
  { city: 'Surrey',             state: 'BC', country: 'CA' },
  { city: 'Kitchener',          state: 'ON', country: 'CA' },
  { city: 'Laval',              state: 'QC', country: 'CA' },
  { city: 'Halifax',            state: 'NS', country: 'CA' },
  { city: 'London',             state: 'ON', country: 'CA' },
  { city: 'Markham',            state: 'ON', country: 'CA' },
  { city: 'Vaughan',            state: 'ON', country: 'CA' },
  { city: 'Gatineau',           state: 'QC', country: 'CA' },
  { city: 'Saskatoon',          state: 'SK', country: 'CA' },
  { city: 'Longueuil',          state: 'QC', country: 'CA' },
  { city: 'Burnaby',            state: 'BC', country: 'CA' },
  { city: 'Regina',             state: 'SK', country: 'CA' },
  { city: 'Richmond',           state: 'BC', country: 'CA' },
  { city: 'Richmond Hill',      state: 'ON', country: 'CA' },
  { city: 'Oakville',           state: 'ON', country: 'CA' },
  { city: 'Burlington',         state: 'ON', country: 'CA' },
  { city: 'Greater Sudbury',    state: 'ON', country: 'CA' },
  { city: 'Sherbrooke',         state: 'QC', country: 'CA' },
  { city: 'Oshawa',             state: 'ON', country: 'CA' },
  { city: 'Abbotsford',         state: 'BC', country: 'CA' },
  { city: 'Coquitlam',          state: 'BC', country: 'CA' },
  { city: 'Kelowna',            state: 'BC', country: 'CA' },
  { city: 'Barrie',             state: 'ON', country: 'CA' },
  { city: 'Lethbridge',         state: 'AB', country: 'CA' },
  { city: 'Red Deer',           state: 'AB', country: 'CA' },
  { city: 'St. Catharines',     state: 'ON', country: 'CA' },
  { city: 'Cambridge',          state: 'ON', country: 'CA' },
  { city: 'Guelph',             state: 'ON', country: 'CA' },
  { city: 'Windsor',            state: 'ON', country: 'CA' },
  { city: 'Moncton',            state: 'NB', country: 'CA' },
  { city: 'Nanaimo',            state: 'BC', country: 'CA' },
  { city: 'St. John\'s',        state: 'NL', country: 'CA' },
  { city: 'Thunder Bay',        state: 'ON', country: 'CA' },
  { city: 'Whitby',             state: 'ON', country: 'CA' },
  { city: 'Victoria',           state: 'BC', country: 'CA' },
  { city: 'Ajax',               state: 'ON', country: 'CA' },
  { city: 'Langley',            state: 'BC', country: 'CA' },
]

// Lookup: city name → state abbreviation (for auto-fill on city select)
export const CITY_STATE_MAP: Record<string, string> = Object.fromEntries(
  MAJOR_CITIES.map(c => [c.city.toLowerCase(), c.state])
)

import type { ComboOption } from '@/components/Combobox'

export const CITY_OPTIONS: ComboOption[] = MAJOR_CITIES.map(c => ({
  value:    c.city,
  label:    c.city,
  sublabel: `${c.state} · ${c.country === 'CA' ? 'Canada' : c.country === 'MX' ? 'Mexico' : 'USA'}`,
  group:    c.country === 'CA' ? 'Canada' : c.country === 'MX' ? 'Mexico' : 'United States',
}))
